# Generated by Django 4.0 on 2021-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBiodata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=50, verbose_name='Nama Depan')),
                ('nama_belakang', models.CharField(max_length=50, verbose_name='Nama Belakang')),
                ('jenis_kelamin', models.CharField(choices=[('Laki-Laki', 'laki-laki'), ('Perempuan', 'perempuan')], max_length=100)),
            ],
        ),
    ]
