# Generated by Django 4.0 on 2021-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daftar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='tanggal_lahir',
            field=models.DateField(blank=True),
        ),
    ]
