# Generated by Django 4.0 on 2021-12-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sosmed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagram',
            name='konten',
            field=models.CharField(default='programming', max_length=100),
            preserve_default=False,
        ),
    ]
